groups:
    - firmware
    - vim

recipes:
    global:
        - dotfiles::inputrc
    mac_os_x:
        - nodejs::default
        - osxdefaults::disable_natural_scrolling
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::enable_standard_function_keys
        - osxdefaults::expand_print_panel_by_default
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_show_all_files
        - osxdefaults::finder_show_file_extensions
        - osxdefaults::finder_show_path_bar
        - osxdefaults::finder_show_status_bar
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::finder_unhide_home
        - osxdefaults::finder_set_preferred_view_style
        - osxdefaults::mail_check_for_new_messages
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::save_to_disk_not_to_iCloud_by_default
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::speed_up_mission_control_animations
        - applications::sublime_text_3

attributes:
    osxdefaults:
        polltime: 1
        preferred_view_style: Nlsv
    dotfiles:
        vimusers:
            - root
            - francois
    git:
        name: Tyler Hoffman
        email: tyhoffman1@gmail.com

    homebrewalt:
        apps:
            - fzf
            - ngrok
            - rename
            - tree
            - z
            - zsh

        cask_apps:
            - 1password
            - alfred
            - appcleaner
            - bettertouchtool
            - cyberduck
            - firefox
            - flux
            - gimp
            - google-chrome
            - plug
            - spotify

